# Generated by Django 4.2.8 on 2023-12-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_api',
            name='age',
        ),
        migrations.RemoveField(
            model_name='data_api',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='data_api',
            name='name',
        ),
        migrations.AddField(
            model_name='data_api',
            name='Chuyen_Mach_Bang_Tay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='data_api',
            name='CongSuat_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='CongSuat_10',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='CongSuat_11',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='CongSuat_12',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='CongSuat_13',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='CongSuat_14',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='CongSuat_15',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='CongSuat_16',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='CongSuat_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='CongSuat_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='CongSuat_4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='CongSuat_5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='CongSuat_6',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='CongSuat_7',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='CongSuat_8',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='CongSuat_9',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DienAp_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DienAp_10',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DienAp_11',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DienAp_12',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DienAp_13',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DienAp_14',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DienAp_15',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DienAp_16',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DienAp_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DienAp_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DienAp_4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DienAp_5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DienAp_6',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DienAp_7',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DienAp_8',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DienAp_9',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DongDien_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DongDien_10',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DongDien_11',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DongDien_12',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DongDien_13',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DongDien_14',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DongDien_15',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DongDien_16',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DongDien_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DongDien_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DongDien_4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DongDien_5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DongDien_6',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DongDien_7',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DongDien_8',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='DongDien_9',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='HieuSuat_10',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='HieuSuat_11',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='HieuSuat_12',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='HieuSuat_13',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='HieuSuat_14',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='HieuSuat_15',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='HieuSuat_16',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='HieuSuat_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='HieuSuat_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='HieuSuat_4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='HieuSuat_5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='HieuSuat_6',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='HieuSuat_7',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='HieuSuat_8',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='HieuSuat_9',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='Thoi_Gian_Chay_Chuyen_Mach',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='Thoi_Gian_Tat_Chuyen_Mach',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='vi_tri_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='vi_tri_10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='vi_tri_11',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='vi_tri_12',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='vi_tri_13',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='vi_tri_14',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='vi_tri_15',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='vi_tri_16',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='vi_tri_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='vi_tri_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='vi_tri_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='vi_tri_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='vi_tri_6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='vi_tri_7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='vi_tri_8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data_api',
            name='vi_tri_9',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
