# Generated by Django 4.2.8 on 2023-12-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0002_remove_data_api_age_remove_data_api_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_api',
            name='HieuSuat_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
