# Generated by Django 4.2.8 on 2023-12-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0005_data_api_read_data_api_read_write_delete_data_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_api_read_write',
            name='Thoi_Gian_Chay_Chuyen_Mach',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='data_api_read_write',
            name='Thoi_Gian_Tat_Chuyen_Mach',
            field=models.TimeField(),
        ),
    ]
