# Generated by Django 4.2.8 on 2023-12-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0007_alter_data_api_read_write_thoi_gian_chay_chuyen_mach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_api_read_write',
            name='Thoi_Gian_Chay_Chuyen_Mach',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data_api_read_write',
            name='Thoi_Gian_Tat_Chuyen_Mach',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
